### PR TITLE
Extra test with numerous parameters, issues and test ID.

### PR DESCRIPTION
**Pull request by volkovs**
Please update pom.xml with `<allure.version>2.0.0-SNAPSHOT</allure.version>`

### CODE REVIEW

**Comment by baev** [comment]
@volkovs maybe rebase the PR and merge it? What are you think?

**Comment by volkovs** [comment]
@Baev 
Had to update Allure version to use `@Parameter`.
I have actually found a bug : ) , but it doesn't affect example, will fix that this week.

**Comment by volkovs** [comment]
@baev could you please check this PR. Than I could add example on SVG attachments on top of this.

**Comment by baev** [comment]
retest this please

**Comment by baev** [comment]
retest this please

**Comment by baev** [comment]
retest this please

**Comment by volkovs** [comment]
retest this please

**Pull request merged**
