### PR TITLE
update example to 2.0-BETA8 and maven plugin

### PR DESCRIPTION
**Pull request by ehborisov**

### CODE REVIEW

**Comment by hemanthsridhar** [comment]
any update on this?

**Comment by baev** [comment]
Already merged to master

**Comment by hemanthsridhar** [comment]
@baev : after serving the report, while viewing after a certain amount of time it fails. Report generation is unstable. Trend line is not showing up as well.

**Comment by baev** [comment]
History feature is only supported in ci environment (using Allure Jenkins/Teamcity/Bamboo plugins)

Can you provide more details on fails?

**Pull request closed without merging**
